version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=login
      - JWT_SECRET=Juan@2025.
      - JWT_EXPIRES_IN=1h
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: login
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  laravel:
    build:
      context: ./laravel-backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel-backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db

  nodejs:
    build:
      context: ./nodejs-backend
    container_name: node_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis